export enum Category {
    Jeans = "Jeans",
    Jackets = "Jackets",
    Shirts = "Shirts",
    Dresses = "Dresses",
    Skirts = "Skirts",
    Pants = "Pants",
    Sweaters = "Sweaters",
    Accessories = "Accessories",
    Outerwear = "Outerwear",
    Tops = "Tops",
    Activewear = "Activewear",
    Formalwear = "Formalwear",
    Sleepwear = "Sleepwear",
    Loungewear = "Loungewear",
    Swimwear = "Swimwear",
    Underwear = "Underwear",
    Sportswear = "Sportswear",
  }
export enum Fabric {
    Denim = "Denim",
    Corduroy = "Corduroy",
    Cotton = "Cotton",
    Leather = "Leather",
    Wool = "Wool",
    Silk = "Silk",
    Polyester = "Polyester",
    Nylon = "Nylon",
    Spandex = "Spandex",
    Rayon = "Rayon",
    Linen = "Linen",
    Velvet = "Velvet",
    Knit = "Knit",
    Synthetic = "Synthetic",
  }
export enum ClotheGender {
    Male = "Male",
    Female = "Female",
    Unisex = "Unisex",
  }
  export enum Season {
    SpringSummer = "Spring/Summer",
    FallWinter = "Fall/Winter",
    Yearly = "Yearly"
}
export enum Color {
    Red = "Red",
    Blue = "Blue",
    Green = "Green",
    Yellow = "Yellow",
    Black = "Black",
    White = "White",
    Gray = "Gray",
    Purple = "Purple",
    Pink = "Pink",
    Orange = "Orange",
    Brown = "Brown",
    Beige = "Beige",
    Navy = "Navy",
    Teal = "Teal",
    Mix = "Mix",
  }